/*

 BLOCK_GAME_BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 3
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define block_game_backgroundWidth 18
#define block_game_backgroundHeight 3
#define block_game_backgroundBank 0

extern unsigned char block_game_background[];

/* End of BLOCK_GAME_BACKGROUND.H */
