/*

 BUILDING_00.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 6
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define building_00Width 5
#define building_00Height 6
#define building_00Bank 0

extern unsigned char building_00[];

/* End of BUILDING_00.H */
