/*

 BUILDING_BACKGROUND_00.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 10
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define building_background_00Width 1
#define building_background_00Height 10
#define building_background_00Bank 0

unsigned char building_background_00[] =
{
  0x7F,0x52,0x52,0x52,0x52,0x52,0x52,0x52,0x52,0x52
};

/* End of BUILDING_BACKGROUND_00.C */
