/*

 BUY_CAR_GAME_TEXT_FINAL_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 3
   Tile set      : minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define buy_car_game_text_final_mapWidth 18
#define buy_car_game_text_final_mapHeight 3
#define buy_car_game_text_final_mapBank 0

extern unsigned char buy_car_game_text_final_map[];

/* End of BUY_CAR_GAME_TEXT_FINAL_MAP.H */
