/*

 BUY_CAR_GAME_BACKGROUND_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define buy_car_game_background_mapWidth 20
#define buy_car_game_background_mapHeight 18
#define buy_car_game_background_mapBank 0

extern unsigned char buy_car_game_background_map[];

/* End of BUY_CAR_GAME_BACKGROUND_MAP.H */
