/*

 BUY_CAR_GAME_TEXT_RESPONSE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 5
   Tile set      : minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define buy_car_game_text_response_mapWidth 20
#define buy_car_game_text_response_mapHeight 5
#define buy_car_game_text_response_mapBank 0

extern unsigned char buy_car_game_text_response_map[];

/* End of BUY_CAR_GAME_TEXT_RESPONSE_MAP.H */
