/*

 CENSOR_GAME_BACKGROUND_TEXT_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 17 x 1
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define censor_game_background_text_mapWidth 17
#define censor_game_background_text_mapHeight 1
#define censor_game_background_text_mapBank 0

unsigned char censor_game_background_text_map[] =
{
  0x17,0x15,0x03,0x7F,0x09,0x11,0x11,0x06,0x7F,0x17,
  0x15,0x15,0x14,0x7F,0x04,0x03,0x06
};

/* End of CENSOR_GAME_BACKGROUND_TEXT_MAP.C */
