/*

 FLAG_POLE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define flag_pole_mapWidth 1
#define flag_pole_mapHeight 5
#define flag_pole_mapBank 0

extern unsigned char flag_pole_map[];

/* End of FLAG_POLE_MAP.H */
