/*

 GAME_OVER.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 7
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game_over_mapWidth 10
#define game_over_mapHeight 7
#define game_over_mapBank 0

extern unsigned char game_over_map[];

/* End of GAME_OVER.H */
