/*

 GAME_TITLE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game_title_mapWidth 20
#define game_title_mapHeight 18
#define game_title_mapBank 0

extern unsigned char game_title_map[];

/* End of GAME_TITLE_MAP.H */
