/*

 GREEN_SQAURE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 6
   Tile set      : minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define green_sqaureWidth 6
#define green_sqaureHeight 6
#define green_sqaureBank 0

extern unsigned char green_sqaure[];

/* End of GREEN_SQAURE.H */
