/*

 HEALTH_GAME_BACKGROUND_BUILDING_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define health_game_background_building_mapWidth 20
#define health_game_background_building_mapHeight 18
#define health_game_background_building_mapBank 0

extern unsigned char health_game_background_building_map[];

/* End of HEALTH_GAME_BACKGROUND_BUILDING_MAP.H */
