/*

 LIE_GAME_BUTTONS_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 1
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define lie_game_buttons_mapWidth 10
#define lie_game_buttons_mapHeight 1
#define lie_game_buttons_mapBank 0

unsigned char lie_game_buttons_map[] =
{
  0x7F,0x06,0x03,0x7F,0x7F,0x7F,0x10,0x1B,0x07,0x16
};

/* End of LIE_GAME_BUTTONS_MAP.C */
