/*

 MINGAME_TITLE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mingame_title_mapWidth 20
#define mingame_title_mapHeight 18
#define mingame_title_mapBank 0

extern unsigned char mingame_title_map[];

/* End of MINGAME_TITLE_MAP.H */
