/*

 MINIGAMES_0_CLEAN.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 126

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define minigames_0Bank 0
/* Start of tile array. */
extern unsigned char minigames_0[];

/* End of MINIGAMES_0_CLEAN.H */
