/*

 SOVIET_SYMBOL_BIG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define soviet_symbol_bigWidth 4
#define soviet_symbol_bigHeight 4
#define soviet_symbol_bigBank 0

extern unsigned char soviet_symbol_big[];

/* End of SOVIET_SYMBOL_BIG.H */
