/*

 SOVIET_SYMBOL_BIG.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define soviet_symbol_bigWidth 4
#define soviet_symbol_bigHeight 4
#define soviet_symbol_bigBank 0

unsigned char soviet_symbol_big[] =
{
  0x40,0x42,0x48,0x4A,0x41,0x43,0x49,0x4B,0x7F,0x46,
  0x43,0x4E,0x45,0x47,0x4D,0x4F
};

/* End of SOVIET_SYMBOL_BIG.C */
