/*

 SPEECH_BOX_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 5
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define speech_box_mapWidth 20
#define speech_box_mapHeight 5
#define speech_box_mapBank 0

extern unsigned char speech_box_map[];

/* End of SPEECH_BOX_MAP.H */
