/*

 SUBWAY_DOORS_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 2
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define subway_doors_mapWidth 2
#define subway_doors_mapHeight 2
#define subway_doors_mapBank 0

unsigned char subway_doors_map[] =
{
  0x67,0x5C,0x66,0x62
};

/* End of SUBWAY_DOORS_MAP.C */
