/*

 SUBWAY_BACKGROUND_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 33 x 18
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define subway_background_mapWidth 33
#define subway_background_mapHeight 18
#define subway_background_mapBank 0

extern unsigned char subway_background_map[];

/* End of SUBWAY_BACKGROUND_MAP.H */
