/*

 SUBWAY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 33 x 18
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define subwayWidth 33
#define subwayHeight 18
#define subwayBank 0

extern unsigned char subway[];

/* End of SUBWAY.H */
