/*

 VICTORY_SCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 14 x 9
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define victory_screenWidth 14
#define victory_screenHeight 9
#define victory_screenBank 0

extern unsigned char victory_screen[];

/* End of VICTORY_SCREEN.H */
