/*

 VOTE_GAME_VOTING_OPTIONS_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 14 x 4
   Tile set      : C:\Users\pfsar\OneDrive\Documents\GitHub\gameboy_micro_game_collection\Resouces\minigames_0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define vote_game_voting_options_mapWidth 14
#define vote_game_voting_options_mapHeight 4
#define vote_game_voting_options_mapBank 0

extern unsigned char vote_game_voting_options_map[];

/* End of VOTE_GAME_VOTING_OPTIONS_MAP.H */
